name: docs_openadmet_models
channels:
  - conda-forge
  - defaults

dependencies:
  - catboost
  - datamol
  - fsspec
  - hyperopt
  - intake
  - intake-parquet
  - joblib
  - lightgbm
  - loguru
  - mordredcommunity
  - numpy
  - pandas
  - pip
  - python >= 3.12,<3.14
  - rdkit
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - splito
  - statsmodels
  - tabulate
  - uncertainty-toolbox
  - xgboost
  - zarr >=3.0.0

  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton

  - pip:
    - email-validator
    - phx-class-registry
    - git+https://github.com/PatWalters/useful_rdkit_utils.git@master
    - -e ../
    - git+https://github.com/openforcefield/openff-sphinx-theme/@main
